### ISSUE TITLE
General review on data notebooks

### ISSUE THREAD

**Issue by HarveySouth** [informatics-lab/spaceapps-2022-mo-bootcamp#1]
Paging @nathan962 for later discussion on repository. I believe current next step to be: Separate notebook into appropriate sections for [NOAA notebook template](https://github.com/geo-yrao/notebook-dev/blob/main/templates/NCAI_Training_Notebook_template%20-%20Distribution%20Copy.ipynb)

**Comment by HarveySouth** [comment]
DATAHUB: either make order strings lowercase otherwise API calls fail, or document this somewhere

**Comment by nathan962** [comment]
@HarveySouth content so far looks really good - I think the biggest challenge will be in 

-  Documenting the Data retrieval 
     - I got some data from datahub but I must've got slightly different data and needed to change indexing throughout the notebook, maybe this will be fine, but giving exact instructions to some of the data you use could be very useful 
     - or give a reason the indexing you have used may not work, perhaps printing data shapes and explaining why we need to index/ not index for certain plots

**Comment by HarveySouth** [comment]
@nathan962 Let me know what you think of the appendix for the DataHub notebook. Also considering hosting the data and downloading from Zenodo or some other service if the order download fails at some point (May be the solution for getting the WOW data anyway). The aircraft notebooks should also run OK following the directions.

**Comment by HarveySouth** [comment]
Added the xarray auto-plot function in 9d50baf

**Comment by HarveySouth** [comment]
Must ensure requirements file is able to run all cells

**Comment by HarveySouth** [comment]
Closed: Past presentation. Review still required but should come as individual issues
