### ISSUE TITLE
Main README 

### ISSUE THREAD

**Issue by nathan962** [informatics-lab/spaceapps-2022-mo-bootcamp#14]
The main README is currently the one for the MO data session - The main readme should probably give an overview of what we are trying to achieve in these sessions and what some outcomes should be. 

Anyone have thoughts on this? @anna-inf-met @hannahbrown7 @stevehadd @HarveySouth

**Comment by hannahbrown7** [comment]
As the intro to Python session is the first, I have a bit of an intro to the bootcamp in my first notebook, but maybe make sense to have in the README? Please feel free to suggest any changes to the wording, this is just something I pull together quickly

Introduction to the data bootcamp

This series of tutorials is being delivered as part of the data bootcamp ahead of the NASA Space Apps Event 2022 hosted in Exeter by the Joint Centre of Excellence in Environmental Intelligence and TechExeter. The data bootcamp consist of three sessions:

1. Introduction to Python for Environmental Science

In this session you will learn about useful Python packages for working with environmental datasets and work through some basic examples for loading and exploring different types of data.

2. Machine Learning with Weather Data

In this session, you will be given a brief introduction to machine learning and have the opportunity to work through a simple (cloud computing) example, specifically using some readily available weather data.

3. Introduction to Weather and Climate Datasets

ADD DESCRIPTION

We will assume you have some experience with programming langauges and ideally have a little bit of knowledge of python. There are a lot of excellent resources on the internet for learning python. This short series of tutorials condenses the most important parts for working specifically with enviromental datasets and provides an overview of tools to make this easier. For a more in depth understanding of python, exploring these exellent tutorials is recommended:

    Software Carpentry: https://swcarpentry.github.io/python-novice-inflammation/index.html
    DataCamp: https://www.datacamp.com/courses/intro-to-python-for-data-science

**Comment by nathan962** [comment]
Looks good to me, shall we add something to the end about conda? For example 

Some of these tutorials require some python package management, we have done this through conda -*insert conda info*-. If you prefer other package management methods please feel free to use them. More information about package management for each session will be contained in that folder.

**Comment by hannahbrown7** [comment]
Sounds good! I think @stevehadd has added specific conda info including yml file for our session in the README in the session folder, so perhaps could add at the end something like "Details about the conda environments used for each session can be found in session folders."

**Comment by nathan962** [comment]
closed with #15
