### ISSUE TITLE
Create .env file template 

### ISSUE THREAD

**Issue by nathan962** [informatics-lab/spaceapps-2022-mo-bootcamp#7]
Create a .env file template, similar to how what is in the markdown 

```
ATMOSPHERIC_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxx
ATMOSPHERIC_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxx
SOME_OTHER_ENV_VAR=2gt2t1t2t7224pZ/*321
```

Also add more instructions for change x,y,z in the file for this to work 

Making this part really obvious and easy to follow will make the content more readable and our lives easier on the day

**Comment by HarveySouth** [comment]
Let me know if this solution is okay with you, I will close the issue for now
