### ISSUE TITLE
Determine method for storing resources

### ISSUE THREAD

**Issue by HarveySouth** [informatics-lab/spaceapps-2022-mo-bootcamp#8]
Should the resources between different presentations be separated, and if so how?

**Comment by nathan962** [comment]
In directory for each one in this repo should do it?

**Comment by stevehadd** [comment]
By resources, do you mean notebooks, or are you thinking of data files @HarveySouth ? If the former, I think @nathan962's suggestion is good.

**Comment by HarveySouth** [comment]
The repo has been restructured for one directory per session, closed by commit 5dff9ad5f99b917473d1362aee7c8da4f761ec2e
